spring:
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

